### ISSUE TITLE
coverage reports attached to merge commits on pull requests

### ISSUE THREAD

**Issue by shinenelson** [gwatts/go-coverage-action#34]
I was experimenting with this action to include it in my workflows. As I was testing **with the `pull_request` event**, I realised that the `git notes` that the action is adding ( by the way, kudos on using `git notes` for storing coverage reports. It is a cool and neat use of the feature 👏 🎉 ), is being added to merge commits and not to the last commit in the pull request.

![image](https://user-images.githubusercontent.com/4771718/198882961-20f1779e-c058-4b01-9278-df526a8fecea.png)

I tried to checkout `github.head_ref` in `actions/checkout` in a vain attempt to see if that would make a difference, but it did not.

![image](https://user-images.githubusercontent.com/4771718/198883346-5cf38616-c2ed-41cf-b256-8859042b1640.png)

---

Upon inspecting the code further, I noticed that the note was being added to `github.context.sha`
https://github.com/gwatts/go-coverage-action/blob/810cf8408bc4d88c4edb030a24f84f090afbbad4/index.js#L68
which, according to the [documentation for GitHub Actions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), points to the **Last merge commit on the `GITHUB_REF` branch**.

This means that there would never be _priorCoverage_ unless there is a companion action run `on:push` event as well which will push coverage reports on the actual commits on the branch.

Can we instead, push the note to the last commit in the pull request so that the notes are always available?

I am not sure whether the context payload https://github.com/gwatts/go-coverage-action/blob/810cf8408bc4d88c4edb030a24f84f090afbbad4/index.js#L75

would have something like `pl.pull_request.head.sha`; but if it does, can we target that please? That way, we would not have to have another action that targets `on:push` events as well in order for the `on:pull_request` workflows work reliably.

**Comment by gwatts** [comment]
Hi @shinenelson - Thanks for the detailed report!

I actually intended this action to be used in conjunction with a `push` event as well on the main branch so that the coverage is tracked for commits on that branch

The problem with relying on notes attached to commits in the PR is that they're essentially lost when/if the branch is rebased or squash-merged as the hash will change.

**Comment by shinenelson** [comment]
> The problem with relying on notes attached to commits in the PR is that they're essentially lost when/if the branch is rebased or squash-merged as the hash will change.

Fair enough. It would be helpful to add this to the ReadMe so that another user who attempts to run this action only `on: pull_request` event would not be confused by this " _intended behaviour_ "
